### ISSUE TITLE
PIL生成图片的时候报错 OSError: cannot open resource

### ISSUE THREAD

**Issue by Cysime** [DrinkOolongTea/splatoon2-bot#1]
环境：Ubuntu Server 20.04，Python3.8，直接使用脚手架nb-cli安装，期间无报错，VPS中运行，故应该是没有中文语言环境的

安装启动后，发送命令报错，看起来像是因为没有加载到中文字体造成的？尝试直接apt安装中文字体 `fonts-wqy-microhei ttf-wqy-zenhei` 没有效果。想请教一下如何能解决，谢谢。

```
04-18 04:08:32 [ERROR] nonebot | Running matcher <Matcher from splatoon2_tools, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.8/dist-packages/splatoon2_tools/__init__.py", line 25, in _handle
    await salmon_run.finish(MessageSegment.image(SplatoonInfo().get_ranked_battle()))
  File "/usr/local/lib/python3.8/dist-packages/splatoon2_tools/utils.py", line 27, in __init__
    self.china_font = ImageFont.truetype(str(china_font_path), 16, encoding="unic")
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 878, in truetype
    return freetype(font)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 875, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by DrinkOolongTea** [comment]
首先感谢你使用，问题已经处理 应该是字体路径的有误， 卸载插件重新安装即可，如果还有问题就查看版本是不是1.1.1，如果不是就使用pip安装pip
 `install nanobot-plugin-splatoon2tools==1.1.1`

**Comment by Cysime** [comment]
感谢回复，更新后已经解决。
